services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - type: bind
        source: default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ssl/certs/nginx-selfsigned.crt
        target: /etc/nginx/ssl/selfsigned.crt
        read_only: true
      - type: bind
        source: ssl/private/nginx-selfsigned.key
        target: /etc/nginx/ssl/selfsigned.key
        read_only: true